[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "npm run start"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 